# Creating Events
mutation CreateEvent($event: CreateEventInput!) {
  createEvent(event: $event) {
    id
  }
}

# Uploading media files
mutation UploadFile($file: Upload!) {
  uploadFile(file: $file) {
    id
    mediaType
  }
}

# Register a user
mutation CreateUser($user: CreateUserInput!) {
  createUser(user: $user) {
    id
  }
}

# Login a user
mutation Login($loginInput: LoginInput!) {
  login(loginInput: $loginInput) {
    accessToken
  }
# User joins an event
mutation JoinEvent($eventId: Int!, $userId: Int!) {
  addParticipantToEvent(eventId: $eventId, userId: $userId)
}

# User leaves an event
mutation LeaveEvent($eventId: Int!, $userId: Int!) {
  removeParticipantFromEvent(eventId: $eventId, userId: $userId)
}
