# Find events by Id
query Event($id: Int!) {
  event(id: $id) {
    id
    title
    description
    startDate
    endDate
    restriction
  }
}

query DiscoverEvents($userId: Int!) {
  discoverEvents(userId: $userId) {
    id
    title
    description
    startDate
    endDate
  }
}

# Gets all related events to a user
query OwnedEvents($userId: Int!) {
  coHostEvents(coHostId: $userId) {
    id
    title
    description
    startDate
    endDate
  }
  hostEvents(hostId: $userId) {
    id
    title
    description
    startDate
    endDate
  }
}

# Get all the events that a user is participating in
query ParticipantEvents($userId: Int!) {
  participantEvents(userId: $userId) {
    id
    endDate
    description
    startDate
    title
  }
}

# Get an array of autocompleted locations as the user types into the text input
query AutocompletedLocations($userInput: String!) {
  getAutocompletedLocations(userInput: $userInput)
}

# Find events by Id and finds participating events of user
query EventPage($eventId: Int!, $userId: Int!) {
  isParticipant(eventId: $eventId, userId: $userId)

  event(id: $eventId) {
    ...EventContent
  }
}

fragment EventContent on Event {
  id
  title
  description
  startDate
  endDate
  restriction
}
