fragment EventPageContent on Event {
  id
  title
  description
  startDate
  endDate
  restriction
  location {
    title
  }
  image {
    id
    mediaType
  }
  host {
    id
    name
  }
}

fragment EventCardContent on Event {
  id
  title
  restriction
  startDate
  location {
    title
  }
  image {
    id
    mediaType
  }
}

query DiscoverEvents {
  discoverEvents {
    ...EventCardContent
  }
}

# Gets all related events to a user
query OwnedEvents {
  coHostEvents {
    id
    title
    restriction
    startDate
    location {
      title
    }
    image {
      id
      mediaType
    }
  }
  hostEvents {
    id
    title
    restriction
    startDate
    location {
      title
    }
    image {
      id
      mediaType
    }
  }
}

# Get all the events that a user is participating in
query ParticipantEvents {
  participantEvents {
    id
    title
    restriction
    startDate
    location {
      title
    }
    image {
      id
      mediaType
    }
  }
}

# Find events by Id and finds participating events of user
query EventPage($eventId: Int!) {
  isParticipant(eventId: $eventId)

  event(id: $eventId) {
    ...EventPageContent
  }
}

query User {
  user {
    id
    name
    description
    avatar {
      id
    }
  }
}

query UserProfile {
  user {
    name
    description
    joinDate
    avatar {
      id
    }
  }

  friendCount
  hostingCount
  portfolioCount
}
